package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Wednesday, October 23, 2013 2:05:33 PM IST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
